version: '3.8'

services:
  # PostgreSQL データベース
  postgres:
    image: postgres:15
    container_name: nuxt_nest_template_postgres
    environment:
      POSTGRES_DB: nuxt_nest_template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nuxt_nest_template_network

  # NestJS バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nuxt_nest_template_backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=nuxt_nest_template
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - nuxt_nest_template_network

  # Nuxt.js フロントエンド
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_nest_template_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - nuxt_nest_template_network

networks:
  nuxt_nest_template_network:
    driver: bridge

volumes:
  postgres_data: